# Generated by Django 4.2.1 on 2023-05-27 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brands", models.CharField(blank=True, max_length=100, null=True)),
                ("categories", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "product_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("seller", models.CharField(blank=True, max_length=100, null=True)),
                ("warranty", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pd_name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField()),
                ("dis_price", models.PositiveIntegerField()),
                ("iamge", models.ImageField(upload_to="product iamge")),
                (
                    "prodcut_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productcategory",
                    ),
                ),
            ],
        ),
    ]
